{"uuid": "f85b20ca-88f2-4ac5-bcf6-dbc5127674a5", "children": ["2496cde3-434d-4f7f-9427-f4761e51f759"], "befores": [{"name": "setup1", "status": "passed", "start": 1674624604230, "stop": 1674624608526}], "afters": [{"name": "setup1::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00616643]\n\t(No symbol) [0x005ABE21]\n\t(No symbol) [0x004AD960]\n\t(No symbol) [0x004D4369]\n\t(No symbol) [0x004FFC76]\n\t(No symbol) [0x004FCA16]\n\t(No symbol) [0x004FBEB4]\n\t(No symbol) [0x00485537]\n\t(No symbol) [0x00485BDE]\n\t(No symbol) [0x00485FCA]\n\tGetHandleVerifier [0x0088A142+2497106]\n\tGetHandleVerifier [0x008B85D3+2686691]\n\tGetHandleVerifier [0x008BBB9C+2700460]\n\tGetHandleVerifier [0x006C3B10+635936]\n\t(No symbol) [0x005B4A1F]\n\t(No symbol) [0x00485277]\n\t(No symbol) [0x00484CB4]\n\tGetHandleVerifier [0x008E432C+2866236]\n\tBaseThreadInitThunk [0x76B500F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x775E7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x775E7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Surekha Gadhave\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Surekha Gadhave\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Surekha Gadhave\\PycharmProjects\\SeleniumWithPython\\conftest.py\", line 29, in setup1\n    driver.close()\n  File \"C:\\Users\\Surekha Gadhave\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\Surekha Gadhave\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Surekha Gadhave\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1674624613795, "stop": 1674624617841}], "start": 1674624604230, "stop": 1674624617841}